create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(320) not null unique,
    created_at timestamp not null default current_timestamp
);

create table if not exists sessions (
    token varchar(36) primary key,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_sessions_user foreign key (user_id) references users(id)
);
