create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(320) not null unique,
    created_at timestamp not null default current_timestamp
);

create table if not exists sessions (
    token varchar(36) primary key,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_sessions_user foreign key (user_id) references users(id)
);

create table if not exists projects (
    id varchar(36) primary key,
    owner_id bigint not null,
    title varchar(200) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_projects_owner foreign key (owner_id) references users(id)
);

create index if not exists idx_projects_owner_created on projects(owner_id, created_at);
