create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(320) not null unique,
    created_at timestamp not null default current_timestamp
);

create table if not exists sessions (
    token varchar(36) primary key,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_sessions_user foreign key (user_id) references users(id)
);

create table if not exists projects (
    id varchar(36) primary key,
    owner_id bigint not null,
    title varchar(200) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_projects_owner foreign key (owner_id) references users(id)
);

alter table projects add column if not exists style varchar(2000);
alter table projects add column if not exists gemini_file_name varchar(200);
alter table projects add column if not exists gemini_file_uri varchar(1000);
alter table projects add column if not exists gemini_root_interaction_id varchar(500);
alter table projects add column if not exists gemini_style_interaction_id varchar(500);
alter table projects add column if not exists gemini_characters_interaction_id varchar(500);

create index if not exists idx_projects_owner_created on projects(owner_id, created_at);

create table if not exists characters (
    id varchar(36) primary key,
    project_id varchar(36) not null,
    position integer not null,
    name varchar(200) not null,
    prompt varchar(4000) not null,
    portrait_status varchar(12) not null default 'PENDING',
    portrait_path varchar(500),
    portrait_error varchar(500),
    portrait_generated_at timestamp,
    portrait_interaction_id varchar(500),
    constraint fk_characters_project foreign key (project_id) references projects(id),
    constraint uq_characters_position unique (project_id, position)
);

alter table characters add column if not exists portrait_status varchar(12) not null default 'PENDING';
alter table characters add column if not exists portrait_path varchar(500);
alter table characters add column if not exists portrait_error varchar(500);
alter table characters add column if not exists portrait_generated_at timestamp;
alter table characters add column if not exists portrait_interaction_id varchar(500);

create table if not exists chapters (
    id varchar(36) primary key,
    project_id varchar(36) not null,
    title varchar(500) not null,
    prompt varchar(4000) not null,
    interaction_id varchar(500),
    constraint fk_chapters_project foreign key (project_id) references projects(id),
    constraint uq_chapters_project unique (project_id)
);

create table if not exists project_steps (
    project_id varchar(36) not null,
    step_key varchar(20) not null,
    position integer not null,
    state varchar(12) not null,
    run_token varchar(36),
    executor_instance_id varchar(36),
    started_at timestamp,
    finished_at timestamp,
    error_message varchar(500),
    primary key (project_id, step_key),
    constraint fk_project_steps_project foreign key (project_id) references projects(id),
    constraint uq_project_steps_position unique (project_id, position)
);

insert into project_steps (project_id, step_key, position, state)
select id, 'STYLE', 1, 'PENDING' from projects
where not exists (select 1 from project_steps where project_steps.project_id = projects.id and step_key = 'STYLE');
insert into project_steps (project_id, step_key, position, state)
select id, 'CHARACTERS', 2, 'PENDING' from projects
where not exists (select 1 from project_steps where project_steps.project_id = projects.id and step_key = 'CHARACTERS');
insert into project_steps (project_id, step_key, position, state)
select id, 'PORTRAITS', 3, 'PENDING' from projects
where not exists (select 1 from project_steps where project_steps.project_id = projects.id and step_key = 'PORTRAITS');
insert into project_steps (project_id, step_key, position, state)
select id, 'CHAPTERS', 4, 'PENDING' from projects
where not exists (select 1 from project_steps where project_steps.project_id = projects.id and step_key = 'CHAPTERS');
insert into project_steps (project_id, step_key, position, state)
select id, 'ILLUSTRATIONS', 5, 'PENDING' from projects
where not exists (select 1 from project_steps where project_steps.project_id = projects.id and step_key = 'ILLUSTRATIONS');
